### ISSUE TITLE
How to show a text when there is no data? 

### ISSUE THREAD

**Issue by blbhargav** [OpenFlutter/flutter_listview_loadmore#10]
I don't know it's a issue or required feature. I want to display a text if there is no data to show(like "No records found").
Thank you.

**Comment by CaiJingLong** [comment]
At present, there is no implementation for empty data alone.
However, it can be achieved in this way:

`textBuilder` will build text : 

Customize your text when the state is `nomore` and the size of the data is 0.

code like this:

```dart
List data = [];

LoadMore(
  isFinish: true, // When no more data is available, set to true.
  textBuilder: (status){
    if(status == LoadMoreStatus.nomore && data.isEmpty){
       return "No records found";
    }
   return DefaultLoadMoreTextBuilder.english(status);
  }
)
```
