### ISSUE TITLE
loadMore + SilverList

### ISSUE THREAD

**Issue by Pitazzo** [OpenFlutter/flutter_listview_loadmore#11]
Hey there,
thanks for these so-needed plugin! Would be possible to get this working with `SilverList`s? It would be great!

Thanks in advance

**Comment by CaiJingLong** [comment]
SliverList is not supported.
There are many plugin packages that support SliverList, you can search them in pub.

**Comment by CaiJingLong** [comment]
Now, 1.0.4 support SliverList.
