### ISSUE TITLE
能否提供一个更改加载文案和加载中占位组件的方法

### ISSUE THREAD

**Issue by VinciShark** [OpenFlutter/flutter_listview_loadmore#3]
比如支持传入自定义的 Widget 作为占位符或者加载文案

**Comment by CaiJingLong** [comment]
https://github.com/OpenFlutter/flutter_listview_loadmore/blob/50f69130bcebbea51d2f80186b44e10d187cc769/loadmore/lib/src/loadmore_widget.dart#L37
https://github.com/OpenFlutter/flutter_listview_loadmore/blob/50f69130bcebbea51d2f80186b44e10d187cc769/loadmore/lib/src/loadmore_widget.dart#L39

每个控件支持传入参数修改文字或根据对应的状态构建widget

----

另外这两个参数也支持全局设置

https://github.com/OpenFlutter/flutter_listview_loadmore/blob/50f69130bcebbea51d2f80186b44e10d187cc769/loadmore/lib/src/loadmore_widget.dart#L11-L12

这两个static的方法是可以自定义的,只要修改这里,并返回即可达到全局设置widget的目的


---

遵循原则局部>全局

**Comment by VinciShark** [comment]
是准备这么实施，还是已经有了该功能？

**Comment by CaiJingLong** [comment]
已有功能

**Comment by VinciShark** [comment]
是否能体现在 README 中，感觉非常多人需要这个功能

**Comment by CaiJingLong** [comment]
文档中有传入属性的说明
不过相信我 文档这东西没人看的
