### ISSUE TITLE
NoSuchMethodError: The method 'then' was called on null.

### ISSUE THREAD

**Issue by Daniyar111** [OpenFlutter/flutter_listview_loadmore#8]
Code is working, but I have an exception 
```
NoSuchMethodError: The method 'then' was called on null.
E/flutter ( 8335): Receiver: null
E/flutter ( 8335): Tried calling: then<dynamic>(Closure: (bool) => Null)
```
exception directs to method ->
```
void loadMore() {
    _updateStatus(LoadMoreStatus.loading);
    widget.onLoadMore().then((v) {
      if (v == true) {
        // 成功，切换状态为空闲
        _updateStatus(LoadMoreStatus.idle);
      } else {
        // 失败，切换状态为失败
        _updateStatus(LoadMoreStatus.fail);
      }
    });
  }

```

**Comment by Daniyar111** [comment]
oh.. this is my mistake) sorry

**Comment by usaikoo** [comment]
helo bro, how do u solve, I have face this problem too now.

**Comment by usaikoo** [comment]
> Code is working, but I have an exception
> 
> ```
> NoSuchMethodError: The method 'then' was called on null.
> E/flutter ( 8335): Receiver: null
> E/flutter ( 8335): Tried calling: then<dynamic>(Closure: (bool) => Null)
> ```
> 
> exception directs to method ->
> 
> ```
> void loadMore() {
>     _updateStatus(LoadMoreStatus.loading);
>     widget.onLoadMore().then((v) {
>       if (v == true) {
>         // 成功，切换状态为空闲
>         _updateStatus(LoadMoreStatus.idle);
>       } else {
>         // 失败，切换状态为失败
>         _updateStatus(LoadMoreStatus.fail);
>       }
>     });
>   }
> ```

helo bro, how do u solve, I have face this problem too now.
